# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "administrators", :force => true do |t|
    t.column "person_id", :integer, :default => 0, :null => false
  end

  add_index "administrators", ["person_id"], :name => "fk_administrators_person_id"

  create_table "best_bets", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
  end

  add_index "best_bets", ["procedure_id"], :name => "fk_best_bets_procedure_id"

  create_table "changes", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "modified_at", :datetime, :null => false
    t.column "title", :string
  end

  add_index "changes", ["procedure_id"], :name => "fk_changes_procedure_id"
  add_index "changes", ["person_id"], :name => "fk_changes_person_id"

  create_table "people", :force => true do |t|
    t.column "email", :string, :default => "", :null => false
    t.column "name", :text, :default => "", :null => false
    t.column "created_at", :datetime, :null => false
  end

  create_table "procedure_comments", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "comment", :text, :default => "", :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  add_index "procedure_comments", ["procedure_id"], :name => "fk_procedure_comments_procedure_id"
  add_index "procedure_comments", ["person_id"], :name => "fk_procedure_comments_person_id"

  create_table "procedure_executes", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "executed_at", :datetime, :null => false
  end

  add_index "procedure_executes", ["procedure_id"], :name => "fk_procedure_executes_procedure_id"
  add_index "procedure_executes", ["person_id"], :name => "fk_procedure_executes_person_id"

  create_table "procedure_views", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "viewed_at", :datetime, :null => false
  end

  add_index "procedure_views", ["procedure_id"], :name => "fk_procedure_views_procedure_id"
  add_index "procedure_views", ["person_id"], :name => "fk_procedure_views_person_id"

  create_table "procedures", :force => true do |t|
    t.column "title", :text, :default => "", :null => false
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "created_at", :datetime, :null => false
    t.column "modified_at", :datetime, :null => false
    t.column "body", :text
    t.column "private", :boolean, :default => false, :null => false
  end

  add_index "procedures", ["person_id"], :name => "fk_procedures_person_id"
  execute "ALTER TABLE procedures ENGINE = MyISAM"
  execute "CREATE FULLTEXT INDEX FullText_Procedures_title_body ON procedures (title,body)"

  create_table "ratings", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
    t.column "rating", :integer, :default => 0, :null => false
    t.column "person_id", :integer, :default => 0, :null => false
  end

  add_index "ratings", ["procedure_id"], :name => "fk_ratings_procedure_id"
  add_index "ratings", ["person_id"], :name => "fk_ratings_person_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "tags", :force => true do |t|
    t.column "procedure_id", :integer, :default => 0, :null => false
    t.column "raw_name", :string, :default => "", :null => false
    t.column "clean_name", :string, :default => "", :null => false
    t.column "person_id", :integer, :default => 0, :null => false
  end

  add_index "tags", ["procedure_id"], :name => "fk_tags_procedure_id"
  add_index "tags", ["person_id"], :name => "fk_tags_person_id"

  create_table "testcases", :force => true do |t|
    t.column "html", :text, :default => "", :null => false
    t.column "action", :text, :default => "", :null => false
    t.column "target", :text, :default => "", :null => false
    t.column "text", :text
    t.column "slop", :text
  end

  create_table "usage_logs", :force => true do |t|
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "procedure_id", :integer
    t.column "created_at", :datetime, :null => false
    t.column "event", :integer, :default => 0, :null => false
    t.column "extra", :text
    t.column "version", :string
  end

  add_index "usage_logs", ["procedure_id"], :name => "fk_usage_logs_procedure_id"
  add_index "usage_logs", ["person_id"], :name => "fk_usage_logs_person_id"

  create_table "user_datas", :force => true do |t|
    t.column "person_id", :integer, :default => 0, :null => false
    t.column "name", :string, :default => "", :null => false
    t.column "value", :text
  end

  add_index "user_datas", ["person_id", "name"], :name => "user_datas_person_id_index"

end
